### ISSUE TITLE
M5Stick hangs

### ISSUE THREAD

**Issue by dclaar** [dclaar/purple_air#13]
I'm seeing some hangs lately with the web-based version. I'm also seeing some tls errors, which _may_ be related.

```
mbedtls_ssl_handshake error: -7280
mbedtls_ssl_handshake error: -7280
mbedtls_ssl_handshake error: -7280
```

When I see it hung and hit control-c, I get:

```
Unhandled exception in thread started by <bound_method>
Traceback (most recent call last):
  File "flowlib/lib/time_ex.py", line 69, in timeCb
KeyboardInterrupt:
Traceback (most recent call last):
  File "main.py", line 64, in <module>
  File "main.py", line 60, in main
  File "main.py", line 55, in main
  File "aqi.py", line 366, in Run
  File "aqi.py", line 361, in Run
  File "aqi.py", line 321, in GetData
  File "aqi.py", line 319, in GetData
  File "m5stickc.py", line 240, in GetURI
  File "m5stickc.py", line 238, in GetURI
  File "nurequests.py", line 110, in request
  File "nurequests.py", line 61, in request
  File "flowlib/lib/time_ex.py", line 69, in timeCb
KeyboardInterrupt:
```
The nurequests:61line is:

```
            s = ussl.wrap_socket(s, server_hostname=host)
```
I am going to throw in a socket timeout to see if that helps.

**Comment by dclaar** [comment]
I haven't seen this sense, so tentatively closing.
