### ISSUE TITLE
Get IndexError from nurequests

### ISSUE THREAD

**Issue by dclaar** [dclaar/purple_air#14]
This is actually an issue in [micropython](https://github.com/micropython/micropython-lib/issues/300) in code [a long ways above urequest](https://github.com/micropython/micropython/pull/5982), so I'm just going to mitigate it.

**Comment by dclaar** [comment]
Well, I already kind of ignore it, but in my fallback.
```
Oops! Fell through!
:None
Traceback (most recent call last):
  File "main.py", line 55, in main
  File "aqi.py", line 366, in Run
  File "aqi.py", line 361, in Run
  File "aqi.py", line 321, in GetData
  File "aqi.py", line 319, in GetData
  File "m5stickc.py", line 240, in GetURI
  File "m5stickc.py", line 238, in GetURI
  File "nurequests.py", line 55, in request
IndexError: list index out of range
```
